### ISSUE TITLE
Anthropic agent failure:  'roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'

### ISSUE THREAD

**Issue by hardye** [etkecc/baibot#13]
I am currently testing the bot using a room-local agent based on the Anthropic provider. The bot responds fine to the initial question, but after two follow-up questions in the same thread it dies with the message:

```
⚠️ Error: There was a problem performing text-generation via the NAME_OF_THE_AGENT agent:

> API error: Error response: error Api error: invalid_request_error messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
```

After that, it won't respond to any commands anymore and simply repeats the error message.

This is the agent's current configuration:

```yaml
base_url: https://api.anthropic.com/v1
api_key: "..."
text_generation:
  model_id: claude-3-5-sonnet-20240620
  prompt: You are a brief, but helpful bot.
  temperature: 1.0
  max_response_tokens: 8192
  max_context_tokens: 204800
```

**To reproduce:**

1. Follow the setup steps for the [Anthropic provider](https://github.com/etkecc/baibot/blob/main/docs/providers.md#anthropic)
2. Create an agent with the configuration shown above.
3. Assign it as a room-specific handler for catch-all.
4. Ask it any question and wait for it to respond.
5. Open the thread created by the bot and respond to it, ask a question, whatever. Do this twice. Observe that the bot will reply without problems.
6. Ask it one more follow-up question. Observe that this time the bot responds with the error-message: _"API error: invalid_request_error messages: roles must alternate between 'user' and 'assistant', but found multiple 'user' roles in a row"_

After this, the only response from the bot is the error message. Starting a new thread will work around this problem, but the same behaviour will occur after the same number of questions and responses.

Another agent using the OpenAI provider does not suffer the same problem. The bot cheerfully deals with long threads.
