### ISSUE TITLE
Failed to parse model ID

### ISSUE THREAD

**Issue by paradoxe35** [etkecc/baibot#22]
When attempting to create a new Anthropic agent with the latest model, I received this error:

<p>
⚠️ Error: The provided configuration does not result in a working agent. The following error was encountered when trying to talk to the agent API:
</p>
<pre>
<code>
    Failed to parse model ID: claude-3-5-sonnet-20241022
</code>
</pre>

I was only able to successfully create an agent using the model: `claude-3-5-sonnet-20240620`

agent yaml:

```yaml
base_url: https://api.anthropic.com/v1
api_key: <API_KEY>
text_generation:
  model_id: claude-3-5-sonnet-20241022
  prompt: 'You are a brief, but helpful bot called {{ baibot_name }} powered by the {{ baibot_model_id }} model. The date/time of this conversation''s start is: {{ baibot_conversation_start_time_utc }}.'
  temperature: 1.0
  max_response_tokens: 8192
  max_context_tokens: 204800
```
