### ISSUE TITLE
API Configuration - Bug Report

### ISSUE THREAD

**Issue by arashatt** [etkecc/baibot#36]
Hello,
I am using ollama llama3.2 model.
The API uses /api/generate endpoint to produce responses, but baibot only recognizes /chat/completion. Shouldn't it infer the type and paths of the given API?

```
docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

### Running The Model
```
docker exec ollama ollama run llama3.2
```

### Testing The Model
 ```
curl http://localhost:11434/api/generate -d '{
                                      "model": "llama3.2",
                                      "prompt":"Why is the sky blue?"
                                    }'
```
### Baibot Configuration

```
     - id: ollama
       provider: ollama
       config:
         base_url: "http://188.245.96.102:11434/api/generate"
         api_key: null

         text_generation:
           model_id: "llama3.2"
           prompt: "You are a brief, but helpful bot called {{ baibot_name }} powered by the {{ baibot_model_id }} model. The date/time of this conversation's start is: {{ baibot_conversation_start_time_utc }}."
           temperature: 1.0
           max_response_tokens: 4096
           max_context_tokens: 128000
```

### Problem
The problem is that baibot requests on /api/generate/chat/completions not /api/generate.
It automatically apends /chat/completions to the endpoint.

![Image](https://github.com/user-attachments/assets/71c841bb-c1bb-4bf6-994b-a5d6d598864e)
