### ISSUE TITLE
Image generation not showing previews

### ISSUE THREAD

**Issue by TheCarrotStick** [etkecc/baibot#38]
Hey, images currently do not have a file extension. From this there is no preview, the file extension is showing as the entire revised prompt

![Image](https://github.com/user-attachments/assets/4d9b3e63-bba1-469b-bcc5-f55931ac6b14)

```yaml
      image_generation:
        model_id: dall-e-3
        size: 1024x1024
        style: vivid
```
