### ISSUE TITLE
Request support for gpt-image-1 and image input

### ISSUE THREAD

**Issue by mwnu** [etkecc/baibot#40]
OpenAI's new image generation model, gpt-image-1, possesses astonishing creative capabilities and supports Create image edit.
Currently, it is not possible to use the new model in baibot by simply modifying the configuration, because this model requires new parameters and no longer supports some old parameters, such as style, hd, and standard image quality.
Reference documentation: https://platform.openai.com/docs/api-reference/images/create

**Comment by spantaleev** [comment]
baibot [v1.7.0](https://github.com/etkecc/baibot/blob/d2660be33c11975027c240411ee18463a9583a14/CHANGELOG.md#2025-05-10-version-170) is now out and among other features, now supports `gpt-image-1`.

You will need the following configuration (see the `image_generation` section):

```yml
base_url: https://api.openai.com/v1
api_key: YOUR_API_KEY_HERE
text_generation:
  model_id: gpt-4.1
  prompt: "You are a brief, but helpful bot called {{ baibot_name }} powered by the {{ baibot_model_id }} model. The date/time of this conversation's start is: {{ baibot_conversation_start_time_utc }}."
  temperature: 1.0
  max_response_tokens: 16384
  max_context_tokens: 128000
speech_to_text:
  model_id: whisper-1
text_to_speech:
  model_id: tts-1-hd
  voice: onyx
  speed: 1.0
  response_format: opus
image_generation:
  model_id: gpt-image-1
  style: null
  size: 1024x1024
  quality: null
```

`style` needs to be `null`, because it's not a supported parameter for `gpt-image-1`.

Also, `quality` had better be `null`, because the OpenAI library we use only supports `standard` and `hd` values for this parameter, which are not valid for the `gpt-image-1` model (it expects `high`, `medium` or `low`).
