### ISSUE TITLE
Feature request: Add ability to use internet search

### ISSUE THREAD

**Issue by derritter88** [etkecc/baibot#42]
It would be a nice to have feature if Baibot would be able to use a search API.
For example I am using SearXNG with my Openweb UI so I can query the internet and still use my local LLM

**Comment by ashleymcdonald** [comment]
A prime example use case of https://github.com/etkecc/baibot/issues/50 :)

**Comment by 0x1af2aec8f957** [comment]
This functionality is similar to the tools (web_search) provided by OpenAI, except that it is more general in nature. A simple example using SearchXNG:

```yml
web_search:
  enabled: true
  provider:
    type: searxng
    url: "http://localhost:8888"

agents:
  static_definitions:
  - id: ollama
    provider: ollama
    config:
      base_url: "http://127.0.0.1:42026/v1"
      api_key: null
      text_generation:
      model_id: "gemma2:2b"
      prompt: "You are a brief, but helpful bot called {{ baibot_name }} powered by the {{ baibot_model_id }} model. The date/time of this conversation's start is: {{ baibot_conversation_start_time_utc }}. The search results for this question on the internet are: {{baibot_web_search_results}}"
      temperature: 1.0
      max_response_tokens: 4096
      max_context_tokens: 128000
```


```rust
let mut prompt_variables = TextGenerationPromptVariables::new(
        bot.name(),
        &controller
            .text_generation_model_id()
            .unwrap_or("unknown-model".to_owned()),
        chrono::Utc::now(),
        conversation.start_time(),
    );

    // Perform web search if configured
    if let Some(search_config) = get_web_search_config(bot) {
        if let Some(query) = extract_user_message_text(&message_context.payload()) {
            tracing::debug!(
                query = &query,
                "Performing web search for query"
            );

            match web_search::search(&query, &search_config).await {
                Ok(results) => {
                    let search_results_text = results.format_for_llm();
                    tracing::debug!(
                        results_count = results.results.len(),
                        "Web search completed successfully"
                    );
                    prompt_variables = prompt_variables.with_web_search_context(search_results_text);
                }
                Err(e) => {
                    tracing::warn!("Web search failed: {:?}", e);
                    // Continue without web search results if search fails
                }
            }
        }
    }
```
