### ISSUE TITLE
Starting, stopping, starting a container will not resume the session and the bot will not start.

### ISSUE THREAD

**Issue by JohanVlugt** [etkecc/baibot#45]
Hello,

With the current config I have the bot can't resume after a stop. Do you know if something is incorrectly configured or that if this is a bug?
Thanks in advance.

Compose file:
```yaml
services:
    baibot:
        image: ghcr.io/etkecc/baibot:latest
        container_name: tools-baibot
        restart: unless-stopped
        volumes:
            - ./config.yaml:/app/config.yml
            - baibot-state:/data
        tmpfs: /tmp:rw,noexec,nosuid,size=1024m

volumes:
    baibot-state:
```

How to recreate the bug.
`docker compose up`
`docker compose down`
`docker compose up`

```log
tools-baibot  | 2025-06-15T08:34:43.074751Z  INFO ThreadId(01) mxlink::init: /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mxlink-1.8.1/src/init.rs:107: Attempting to re-use previous session found in `/data/session.json`
tools-baibot  | 2025-06-15T08:34:44.225197Z ERROR ThreadId(08) matrix_sdk::encryption: /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/matrix-sdk-0.12.0/src/encryption/mod.rs:1667: Couldn't setup and resume recovery Sdk(Http(Api(Server(ClientApi(Error { status_code: 401, body: Standard { kind: MissingToken, message: "Missing access token" } })))))
tools-baibot  | 2025-06-15T08:34:44.236609Z ERROR ThreadId(02) matrix_sdk::encryption::recovery: /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/matrix-sdk-0.12.0/src/encryption/recovery/mod.rs:637: Couldn't update the recovery state: Sdk(Http(Api(Server(ClientApi(Error { status_code: 401, body: Standard { kind: MissingToken, message: "Missing access token" } })))))
tools-baibot  | 2025-06-15T08:34:44.248211Z  WARN ThreadId(01) mxlink::init: /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mxlink-1.8.1/src/init.rs:273: Whoami sanity check with a potentially-transient error.. Retrying after a delay.. delay=2s
```

I checked the `/data/session.json` and it seems there.
When I remove this session.json file the bot successfully starts up again.
